# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2


# `run-as:`: Optional sequence. Available to Linux users only. Specifies a Linux user that runs commands in this buildspec file. run-as grants the specified user read and run permissions. When you specify run-as at the top of the buildspec file, it applies globally to all commands. If you don't want to specify a user for all buildspec file commands, you can specify one for commands in a phase by using run-as in one of the phases blocks. If run-as is not specified, then all commands run as the root user.
# run-as: root

# `env:`: Optional sequence. Represents information for one or more custom environment variables.
env:
  # `env/shell`: Optional sequence. Specifies the supported shell for Linux or Windows operating systems.  For Linux, supported shell tags are:
  #   - bash
  #   - /bin/sh
  shell: bash
  parameter-store:
    DOCKERHUB_PASS_PARAM: /dockerhub-access-token-for-pwighton

phases:
  install:
    - export DOCKERHUB_PASS=$DOCKERHUB_PASS_PARAM
    - docker login --username pwighton --password $DOCKERHUB_PASSWD

  build:
    on-failure: ABORT
    commands:
      - make fs-build

  post_build:
    on-failure: ABORT | CONTINUE
    commands:
      - docker push pwighton/fs-dev-build:latest
