# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  shell: bash
  # https://stackoverflow.com/questions/58216549/how-to-retrieve-secret-manager-data-in-buildspec-yaml
  parameter-store:
    DOCKERHUB_PASS_PARAM: /dockerhub-access-token-for-pwighton
    FS_LICENSE_PARAM: /freesurfer-ci-license
            
phases:
  install:
    #run-as: Linux-user-name
    on-failure: ABORT
    commands:
      - export DOCKERHUB_PASS=$DOCKERHUB_PASS_PARAM
      - export FS_LICENSE=$FS_LICENSE_PARAM
      - docker login --username pwighton --password $DOCKERHUB_PASS      
      - git clone https://github.com/pwighton/neurodocker.git
      - cd neurodocker
      - git checkout 20210226-fs-source
      - conda create -n nd-dev python=3.6.6
      - conda activate nd-dev
      - python -m pip install --no-cache-dir --editable .[all]
    #finally:
    #  - command
  #pre_build:
    #run-as: Linux-user-name
    #on-failure: ABORT
    #commands:
    #finally:

  build:
    #run-as: Linux-user-name
    on-failure: ABORT
    commands:
      - neurodocker generate docker --base-image ubuntu:xenial --pkg-manager apt --yes --freesurfer license_base64=cGF1bEBjb3J0aWNvbWV0cmljcy5jb20KMzA0NDQKICpDZ3lrR3o2bnNYaGcKIEZTVXQweHY5UmlGcWMK method=source repo=https://github.com/pwighton/freesurfer.git version=dev minimal=off infant_module=on install_python_deps=on distribute_fspython=on | docker build --no-cache -t pwighton/fs-dev-monolith -

