# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  shell: bash
            
phases:
  install:
    on-failure: ABORT
    commands:
      - pip install neurodocker docker
  build:
    on-failure: ABORT
    commands:
      #- docker pull pwighton/fs-infant-dev
       - docker pull bash
  post_build:
    on-failure: ABORT
    commands:
      - docker run --security-opt seccomp:unconfined --rm -it -d --name container-to-min bash /bin/bash
      - cmd1="echo hello world"
      - yes | neurodocker-minify --container container-to-min --dirs-to-prune /opt --commands "$cmd1" docker export container-to-min | docker import - pwighton/container-to-min--test
      - docker push pwighton/container-to-min--test
