# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  shell: bash
  # https://stackoverflow.com/questions/58216549/how-to-retrieve-secret-manager-data-in-buildspec-yaml
  parameter-store:
    DOCKERHUB_PASS_PARAM: /dockerhub-access-token-for-pwighton
    FS_LICENSE_PARAM: /freesurfer-ci-license2
            
phases:
  install:
    on-failure: ABORT
    commands:
      - export DOCKERHUB_PASS=$DOCKERHUB_PASS_PARAM
      - export FS_LICENSE=$FS_LICENSE_PARAM
      - echo "DOCKERHUB_PASS: "$DOCKERHUB_PASS_PARAM
      - echo "FS_LICENSE_PARAM: "$FS_LICENSE_PARAM
