# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  shell: bash
  # https://stackoverflow.com/questions/58216549/how-to-retrieve-secret-manager-data-in-buildspec-yaml
  parameter-store:
    DOCKERHUB_PASS_PARAM: /dockerhub-access-token-for-pwighton
    FS_LICENSE_PARAM: /freesurfer-ci-license
            
phases:
  install:
    on-failure: ABORT
    commands:
      - export DOCKERHUB_PASS=$DOCKERHUB_PASS_PARAM
      - export FS_LICENSE=$FS_LICENSE_PARAM
      - docker login --username pwighton --password $DOCKERHUB_PASS
      # even though we use `pwighton/neurodocker:latest` to create the Dockerfile
      # we need neurodocker for `neurodocker minify`
      - pip install neurodocker
  build:
    on-failure: ABORT
    commands:
      - ND="docker run pwighton/neurodocker:latest" FS_LICENSE_BASE64=$FS_LICENSE make fs-infant-dev
      - docker push pwighton/fs-infant-dev:latest
      #- docker pull pwighton/fs-infant-dev:latest
