# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  shell: bash
  # https://stackoverflow.com/questions/58216549/how-to-retrieve-secret-manager-data-in-buildspec-yaml
  parameter-store:
    DOCKERHUB_PASS_PARAM: /dockerhub-access-token-for-pwighton
    FS_LICENSE_PARAM: /freesurfer-ci-license
            
phases:
  install:
    on-failure: ABORT
    commands:
      - export DOCKERHUB_PASS=$DOCKERHUB_PASS_PARAM
      - export FS_LICENSE=$FS_LICENSE_PARAM
      - docker login --username pwighton --password $DOCKERHUB_PASS
      - aws ecr get-login --no-include-email | sh
  build:
    on-failure: ABORT
    commands:
      - docker run hello-world
      - docker tag hello-world 701847355435.dkr.ecr.us-east-2.amazonaws.com/test
  post_build:
    on-failure: ABORT
    commands:
      - docker push 701847355435.dkr.ecr.us-east-2.amazonaws.com/test
