# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  shell: bash
  # https://stackoverflow.com/questions/58216549/how-to-retrieve-secret-manager-data-in-buildspec-yaml
  parameter-store:
    DOCKERHUB_PASS_PARAM: /dockerhub-access-token-for-pwighton
                
phases:
  install:
    on-failure: ABORT
    commands:
      - export DOCKERHUB_PASS=$DOCKERHUB_PASS_PARAM
      - docker login --username pwighton --password $DOCKERHUB_PASS
      - pip install neurodocker docker
  build:
    on-failure: ABORT
    commands:
      - docker pull pwighton/fs-infant-dev
  post_build:
    on-failure: ABORT
    commands:
      - docker run --security-opt seccomp:unconfined --rm -it -d --name container-to-min --entrypoint /bin/bash pwighton/fs-infant-dev
      - sleep 1
      - cmd1="echo hello world"
      - yes | neurodocker-minify --container container-to-min --dirs-to-prune /opt --commands "$cmd1" 
      - docker export container-to-min | docker import - pwighton/container-to-min--test
