# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  shell: bash
            
phases:
  install:
    on-failure: ABORT
    commands:
      - pip install neurodocker
  build:
    on-failure: ABORT
    commands:
      - docker pull library/bash
  post_build:
    on-failure: ABORT
    commands:
      - docker run --rm -it -d --name container-to-min library/bash
      - cmd1="echo hello world"
      - yes | neurodocker-minify --container container-to-min --dirs-to-prune /opt --commands "$cmd1" docker export container-to-min | docker import - pwighton/container-to-min--test
